// <auto-generated />
using System;
using ITHelper.Infranstrucure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITHelper.Infranstrucure.Migrations
{
    [DbContext(typeof(ITHelperContext))]
    [Migration("20240809133031_Blog-okunmaSayisi")]
    partial class BlogokunmaSayisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Blog", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuncelleyenKullaniciID")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OkunmaSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("OlusturanKullaniciID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ozet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogID");

                    b.HasIndex("GuncelleyenKullaniciID");

                    b.HasIndex("OlusturanKullaniciID");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.BlogEtiket", b =>
                {
                    b.Property<int>("BlogEtiketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogEtiketID"));

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<int>("EtiketID")
                        .HasColumnType("int");

                    b.HasKey("BlogEtiketID");

                    b.HasIndex("BlogID");

                    b.HasIndex("EtiketID");

                    b.ToTable("BlogEtiketler");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Etiket", b =>
                {
                    b.Property<int>("EtiketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtiketID"));

                    b.Property<string>("EtiketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EtiketID");

                    b.ToTable("Etiketler");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KullaniciAktifligi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Blog", b =>
                {
                    b.HasOne("ITHelper.Infranstrucure.Entities.Kullanici", "GuncelleyenKullanici")
                        .WithMany()
                        .HasForeignKey("GuncelleyenKullaniciID");

                    b.HasOne("ITHelper.Infranstrucure.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciID");

                    b.Navigation("GuncelleyenKullanici");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.BlogEtiket", b =>
                {
                    b.HasOne("ITHelper.Infranstrucure.Entities.Blog", "Blog")
                        .WithMany("BlogEtiketler")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITHelper.Infranstrucure.Entities.Etiket", "Etiket")
                        .WithMany("BlogEtiketler")
                        .HasForeignKey("EtiketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Etiket");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Blog", b =>
                {
                    b.Navigation("BlogEtiketler");
                });

            modelBuilder.Entity("ITHelper.Infranstrucure.Entities.Etiket", b =>
                {
                    b.Navigation("BlogEtiketler");
                });
#pragma warning restore 612, 618
        }
    }
}
